import { notFound } from "next/navigation";

interface ReportPageProps {
  params: Promise<{ id: string }>;
  searchParams: Promise<{ period?: string; date?: string }>;
}

export default async function GenerateReportPage({
  params,
  searchParams,
}: ReportPageProps) {
  const { id: store_id } = await params;
  const { period = "month", date } = await searchParams;

  const targetDate = date ? new Date(date) : new Date();

  // MOCK DATA
  const mockStore = {
    id: store_id,
    name: "Apex Retail Solutions HQ",
  };

  const mockLowStockItems = [
    { id: "p1", name: "Wireless Ergonomic Mouse", sku: "MS-ERG-01", stock: 4 },
    {
      id: "p2",
      name: "Mechanical Keyboard (Red Switches)",
      sku: "KB-MEC-RD",
      stock: 2,
    },
    { id: "p3", name: 'UltraWide Monitor 34"', sku: "MON-UW-34", stock: 7 },
    { id: "p4", name: "USB-C Multi-Port Hub", sku: "HUB-USBC-09", stock: 0 },
    {
      id: "p5",
      name: "Premium Leather Desk Pad",
      sku: "PAD-LTH-BRN",
      stock: 9,
    },
  ];

  const totalRevenue = 24850.0;
  const growthPercentage = 14.2;
  const managerName = "Sarah Jenkins";

  if (!mockStore) notFound();

  return (
    <div className="min-h-screen bg-white p-8 max-w-4xl mx-auto text-gray-900 print:p-0 print:max-w-full">
      {/* Print Controls (Hidden on the actual PDF) */}
      <div className="mb-6 p-4 bg-blue-50 border border-blue-200 rounded-xl flex items-center justify-between print:hidden">
        <div className="flex flex-col">
          <span className="text-sm font-semibold text-blue-900">
            Mock Data Preview Mode
          </span>
          <span className="text-xs text-blue-700">
            Database queries are bypassed. Ready to print or save as PDF.
          </span>
        </div>
        {/* FIXED: Removed onClick and added an id */}
        <button
          id="manual-print-trigger"
          className="px-4 py-2 bg-blue-600 text-white text-sm font-medium rounded-lg hover:bg-blue-700 transition-colors shadow-sm"
        >
          Open Print Dialog
        </button>
      </div>

      {/* --- PDF DOCUMENT START --- */}
      <header className="border-b-2 border-gray-200 pb-6 flex justify-between items-start">
        <div>
          <h1 className="text-2xl font-bold tracking-tight">
            {mockStore.name}
          </h1>
          <p className="text-sm text-gray-500 mt-1 uppercase tracking-wider font-medium">
            Performance Report — {period}ly
          </p>
          <p className="text-xs text-gray-400 mt-0.5">Store ID: {store_id}</p>
        </div>
        <div className="text-right text-sm text-gray-500">
          <p>
            Generated by:{" "}
            <span className="font-medium text-gray-800">{managerName}</span>
          </p>
          <p>
            Date:{" "}
            {targetDate.toLocaleDateString("en-US", {
              month: "long",
              year: "numeric",
              day: "numeric",
            })}
          </p>
        </div>
      </header>

      <section className="my-8">
        <h2 className="text-sm font-bold text-gray-400 uppercase tracking-wider mb-4">
          Executive Summary
        </h2>
        <div className="grid grid-cols-2 gap-4">
          <div className="border border-gray-200 rounded-xl p-5 bg-gray-50/50">
            <p className="text-sm text-gray-500 font-medium">Total Revenue</p>
            <p className="text-3xl font-bold mt-1">
              {new Intl.NumberFormat("en-US", {
                style: "currency",
                currency: "USD",
              }).format(totalRevenue)}
            </p>
          </div>
          <div className="border border-gray-200 rounded-xl p-5 bg-gray-50/50">
            <p className="text-sm text-gray-500 font-medium">
              Growth vs Previous Period
            </p>
            <p className="text-3xl font-bold mt-1 text-green-600">
              +{growthPercentage}%
            </p>
          </div>
        </div>
      </section>

      <section className="my-8 print:break-inside-avoid">
        <h2 className="text-sm font-bold text-gray-400 uppercase tracking-wider mb-4">
          Sales Trends (1 Month)
        </h2>
        <div className="border border-gray-200 rounded-xl h-64 flex items-center justify-center bg-gray-50 text-gray-400 text-sm border-dashed">
          [Line Chart Component Visual Trend — Mocked]
        </div>
      </section>

      <section className="my-8 print:break-inside-avoid">
        <h2 className="text-sm font-bold text-gray-400 uppercase tracking-wider mb-4">
          Low Stock Alerts
        </h2>
        {mockLowStockItems.length === 0 ? (
          <p className="text-sm text-gray-500">
            All products are adequately stocked.
          </p>
        ) : (
          <div className="border border-gray-200 rounded-xl overflow-hidden">
            <table className="min-w-full divide-y divide-gray-200 text-sm">
              <thead className="bg-gray-50">
                <tr>
                  <th className="px-4 py-3 text-left font-semibold text-gray-700">
                    Product Name
                  </th>
                  <th className="px-4 py-3 text-left font-semibold text-gray-700">
                    SKU
                  </th>
                  <th className="px-4 py-3 text-right font-semibold text-gray-700">
                    Stock Remaining
                  </th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-200 bg-white">
                {mockLowStockItems.map((item) => (
                  <tr key={item.id}>
                    <td className="px-4 py-3 font-medium text-gray-900">
                      {item.name}
                    </td>
                    <td className="px-4 py-3 text-gray-500">{item.sku}</td>
                    <td className="px-4 py-3 text-right font-semibold text-red-600">
                      {item.stock === 0 ? "OUT OF STOCK" : item.stock}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </section>
      {/* --- PDF DOCUMENT END --- */}

      {/* FIXED: Vanilla JS binds the click listener natively on the client side */}
      <script
        dangerouslySetInnerHTML={{
          __html: `
            // 1. Automatically pop open the print dialog on load
            setTimeout(() => {
              window.print();
            }, 600);

            // 2. Wire up the backup button using standard DOM listeners
            document.getElementById('manual-print-trigger')?.addEventListener('click', () => {
              window.print();
            });
          `,
        }}
      />
    </div>
  );
}
