import { notFound } from "next/navigation";
import { canShowAdmin } from "@/src/lib/canUser";
import { redirect } from "next/navigation";
import { prisma } from "@/src/lib/prisma";
import { isLoggedIn } from "@/src/lib/isLoggedIn";
import { getRevenueStats } from "@/src/lib/revenue-utils";
import Trend from "@/src/app/admin/[id]/components/Trend";
import { getTrendData } from "@/src/lib/trend";
import PrintControls from "@/src/app/admin/[id]/components/PrintControls";
import { getStoreCurrency } from "@/src/lib/data/store";

interface ReportPageProps {
  params: Promise<{ id: string }>;
  searchParams: Promise<{ period?: string; date?: string }>;
}

export default async function GenerateReportPage({
  params,
  searchParams,
}: ReportPageProps) {
  const { id: store_id } = await params;
  const { period = "month", date } = await searchParams;
  const gotSearchParams = { period, date };

  const canGenerate = await canShowAdmin(store_id, "report");
  const canShowTrend = await canShowAdmin(store_id, "trend");

  if (canGenerate.status !== 200) {
    redirect(`/admin/${store_id}`);
  }
  const session = await isLoggedIn();

  const targetDate = date ? new Date(date) : new Date();

  // 1. Fetch the store and its settings
  const store = await prisma.store.findUnique({
    where: {
      id: store_id,
    },
    select: {
      id: true,
      store_name: true,
      settings: true,
    },
  });

  if (!store) {
    notFound(); // Cleaner than throwing an Error in Next.js
  }

  // Extract the threshold from the store's settings
  const threshold = store.settings.low_stock_threshold;

  // 2. Fetch products below the threshold
  const products = await prisma.product.findMany({
    where: {
      store_id: store_id,
      quantity: {
        lte: threshold, // Less than or equal to the threshold
      },
      is_deleted: false, // Ensure we don't fetch deleted products
    },
    select: {
      id: true,
      name: true,
      sku: true,
      quantity: true,
    },
    orderBy: {
      quantity: "asc", // Order by lowest stock first
    },
  });

  // 3. Map the data to match your component's expected format
  const storeData = {
    id: store.id,
    name: store.store_name,
  };

  const lowStockItems = products.map((item) => ({
    id: item.id,
    name: item.name,
    sku: item.sku,
    stock: item.quantity, // Mapping Prisma's 'quantity' to 'stock'
  }));

  // FIXED: Spread the search params and inject the storeId
  const revenueData = await getRevenueStats({
    ...gotSearchParams,
    storeId: store_id,
  });

  const totalRevenue = revenueData.currentRev;
  const growthPercentage = revenueData.percentageChange;
  const managerName = session.user.name || "Unknown Manager";

  const colorClass =
    growthPercentage === 0
      ? "text-gray-500"
      : growthPercentage > 0
        ? "text-green-500"
        : "text-red-500";

  const trendPayload = canShowTrend
    ? await getTrendData(store_id, gotSearchParams)
    : null;
  const periodLabel = period === "day" ? "daily" : `${period}ly`;

  const currencyResult = await getStoreCurrency(store_id);
  const currency = currencyResult.success
    ? (currencyResult.data as string)
    : "PHP";

  const formattedRevenue = new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: currency,
  }).format(totalRevenue);

  return (
    <div className="min-h-screen bg-white p-8 max-w-4xl mx-auto text-gray-900 print:p-0 print:max-w-full">
      <PrintControls />
      <header className="border-b-2 border-gray-200 pb-6 flex justify-between items-start">
        <div>
          <h1 className="text-2xl font-bold tracking-tight">
            {storeData.name}
          </h1>
          <p className="text-sm text-gray-500 mt-1 uppercase tracking-wider font-medium">
            Performance Report — {periodLabel}
          </p>
          <p className="text-xs text-gray-400 mt-0.5">Store ID: {store_id}</p>
        </div>
        <div className="text-right text-sm text-gray-500">
          <p>
            Generated by:{" "}
            <span className="font-medium text-gray-800">{managerName}</span>
          </p>
          <p>
            Start Date:{" "}
            {targetDate.toLocaleDateString("en-US", {
              month: "long",
              year: "numeric",
              day: "numeric",
            })}
          </p>
        </div>
      </header>

      <section className="my-8">
        <h2 className="text-sm font-bold text-gray-400 uppercase tracking-wider mb-4">
          Executive Summary
        </h2>
        <div className="grid grid-cols-2 gap-4">
          <div className="border border-gray-200 rounded-xl p-5 bg-gray-50/50">
            <p className="text-sm text-gray-500 font-medium">Total Revenue</p>
            <p className="text-3xl font-bold mt-1">{formattedRevenue}</p>
          </div>
          <div className="border border-gray-200 rounded-xl p-5 bg-gray-50/50">
            <p className="text-sm text-gray-500 font-medium">
              Growth vs Previous Period
            </p>
            <p className={`text-3xl font-bold mt-1 ${colorClass}`}>
              {growthPercentage > 0 ? "+" : ""}
              {growthPercentage}%
            </p>
          </div>
        </div>
      </section>

      <section className="my-8 print:break-inside-avoid">
        <h2 className="text-sm font-bold text-gray-400 uppercase tracking-wider mb-4">
          Sales Trends (1 Month)
        </h2>
        {canShowTrend && trendPayload ? (
          <Trend
            data={trendPayload.chartData}
            totalRevenue={trendPayload.totalRevenue}
            currency={currency}
          />
        ) : null}
      </section>

      <section className="my-8">
        <h2 className="text-sm font-bold text-gray-400 uppercase tracking-wider mb-4">
          Low Stock Alerts
        </h2>
        {lowStockItems.length === 0 ? (
          <p className="text-sm text-gray-500">
            All products are adequately stocked.
          </p>
        ) : (
          <div className="border border-gray-200 rounded-xl overflow-hidden">
            <table className="min-w-full divide-y divide-gray-200 text-sm">
              <thead className="bg-gray-50">
                <tr>
                  <th className="px-4 py-3 text-left font-semibold text-gray-700">
                    Product Name
                  </th>
                  <th className="px-4 py-3 text-left font-semibold text-gray-700">
                    SKU
                  </th>
                  <th className="px-4 py-3 text-right font-semibold text-gray-700">
                    Stock Remaining
                  </th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-200 bg-white">
                {lowStockItems.map((item) => (
                  <tr key={item.id}>
                    <td className="px-4 py-3 font-medium text-gray-900">
                      {item.name}
                    </td>
                    <td className="px-4 py-3 text-gray-500">{item.sku}</td>
                    <td className="px-4 py-3 text-right font-semibold text-red-600">
                      {item.stock === 0 ? "OUT OF STOCK" : item.stock}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </section>
      {/* --- PDF DOCUMENT END --- */}
    </div>
  );
}
